apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-secrets
  labels:
    {{- include "genai-cloudops.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  postgres-password: {{ .Values.postgres.password | default "defaultpassword" | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" 
    (.Values.postgres.username | default "postgres") 
    (.Values.postgres.password | default "defaultpassword") 
    (include "genai-cloudops.fullname" .) 
    (.Values.postgres.database | default "genai_cloudops") | b64enc | quote }}
  
  # Application secrets
  secret-key: {{ .Values.backend.secretKey | default "change-this-in-production-very-secret-key" | b64enc | quote }}
  
  # GenAI API keys (optional)
  {{- if .Values.genai.groqApiKey }}
  groq-api-key: {{ .Values.genai.groqApiKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.genai.openaiApiKey }}
  openai-api-key: {{ .Values.genai.openaiApiKey | b64enc | quote }}
  {{- end }}
---
{{- if .Values.oci.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-oci-config
  labels:
    {{- include "genai-cloudops.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.oci.configFile }}
  config: {{ .Values.oci.configFile | b64enc | quote }}
  {{- else }}
  config: {{ printf "[%s]\nuser=%s\nfingerprint=%s\ntenancy=%s\nregion=%s\nkey_file=/root/.oci/key.pem" 
    (.Values.oci.profile | default "DEFAULT")
    (.Values.oci.userId | default "")
    (.Values.oci.fingerprint | default "")
    (.Values.oci.tenancyId | default "")
    (.Values.oci.region | default "us-ashburn-1") | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.oci.privateKey }}
  key.pem: {{ .Values.oci.privateKey | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.oci.publicKey }}
  key_public.pem: {{ .Values.oci.publicKey | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-tls
  labels:
    {{- include "genai-cloudops.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
---
{{- if .Values.redis.enabled and .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-redis-auth
  labels:
    {{- include "genai-cloudops.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
{{- end }} 